services:
  # PostgreSQL Database Service
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=OmLokhande2004
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  # FastAPI Application Service
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
